_target_: pytorch_lightning.Trainer

accelerator: gpu
devices: 1

min_epochs: 5
max_epochs: 100

# number of validation steps to execute at the beginning of the training
num_sanity_val_steps: 1

# fastdev
fast_dev_run: False

#log_every_n_steps: 100
#
#val_check_interval: 0.5

precision: 32
