_target_: pytorch_lightning.Trainer

accelerator: gpu
devices: 1

min_epochs: 1
max_epochs: 10

# number of validation steps to execute at the beginning of the training
num_sanity_val_steps: 0

# fastdev
fast_dev_run: False

log_every_n_steps: 1000

#val_check_interval: 1
check_val_every_n_epoch: 1

precision: bf16
