
_target_: mmdc_downstream.models.lightning.lai_regression.MMDCDownstreamRegressionLitModule
lr: 0.001
resume_from_checkpoint: null

# To choose from [experts, lat_S1, lat_S2, S2, S1_asc, S2_desc]
input_data: lat_S2

model:
  _target_: mmdc_downstream.models.torch.lai_regression.MMDCDownstreamRegressionModule
  config:
    _target_: mmdc_downstream.models.datatypes.RegressionConfig
    reg_model:
      hidden_sizes: [5]
      input_size: 6
      output_size: 1

model_snap:
  _target_: mmdc_downstream.snap.lai_snap.BVNET
  device: cuda
  ver: "2"
  variable: lai

# To choose from ["RSE", "R2", "MAE", "MAPE"]
metrics_list : ["RSE", "R2", "MAE", "MAPE"]

# To choose from ["RMSE", "MSE", "MAE"]
losses_list : ["MSE"]

model_mmdc:
  _target_: mmdc_downstream.mmdc_model.model.PretrainedMMDC
  pretrained_path: "/work/scratch/data/kalinie/MMDC/results/latent/checkpoints/mmdc_full/2024-02-05_09-45-27"
  model_name: last
  model_type: baseline   # to choose from ["baseline", "experts"]

stats_path: /work/scratch/data/kalinie/MMDC/results/latent/checkpoints/mmdc_full/2024-02-05_09-45-27/stats.pt
