
_target_: mmdc_downstream_lai.models.lightning.lai_regression_csv.MMDCLAILitModule
lr: 0.0001
resume_from_checkpoint: null

model:
  _target_: mmdc_downstream_lai.models.torch.lai_regression.MMDCDownstreamRegressionModule
  config:
    _target_: mmdc_downstream_lai.models.datatypes.RegressionConfig
    reg_model:
      hidden_sizes: [ 16, 16 ]
      input_size: 6
      output_size: 1


# To choose from ["RSE", "R2", "MAE", "MAPE"]
metrics_list : ["RSE", "R2", "MAE", "MAPE"]

# To choose from ["RMSE", "MSE", "MAE"]
losses_list : ["RMSE"]
