
_target_: mmdc_singledate.models.lightning.full.MMDCFullLitModule
lr: 0.0001
resume_from_checkpoint: null

model:
  _target_: mmdc_downstream.models.torch.lai_regression.MMDCDownstreamRegressionModule
  config:
    _target_: mmdc_downstream.models.datatypes.RegressionConfig
    mmdc_model:
      pretrained_path: null
      model_name: null
    reg_model:
      hidden_sizes: [8, 16, 8]
