
_target_: mmdc_downstream_pastis.models.lightning.pastis_utae_semantic.PastisUTAE
lr: 0.001
resume_from_checkpoint: ${oc.env:WORK}/results/MMDC/results/pastis/checkpoints/pastis_oe_concat_utae/2024-05-22_19-55-24/epoch_003.ckpt

model:
  _target_: mmdc_downstream_pastis.models.torch.utae_fusion.UTAEFusion
  input_dim:
    S2: 10
    S1_ASC: 3
    S1_DESC: 3
  fusion: concat
  satellites: [ "S2", "S1_ASC", "S1_DESC" ]

metrics_list : ["cross_entropy"]

# To choose from ["RMSE", "MSE", "MAE"]
losses_list : ["cross_entropy"]
