
_target_: mmdc_downstream_pastis.models.lightning.pastis_utae_semantic.PastisUTAE
lr: 0.001
resume_from_checkpoint: null #/work/scratch/data/kalinie/MMDC/results/pastis/checkpoints/pastis_utae/2024-02-20_16-30-23/epoch_098.ckpt

model:
  _target_: mmdc_downstream_pastis.models.torch.utae_fusion.UTAEFusion
  input_dim:
    S1: 12
    S2: 12
  fusion: mean

metrics_list : ["cross_entropy"]

# To choose from ["RMSE", "MSE", "MAE"]
losses_list : ["cross_entropy"]
