
_target_: mmdc_downstream_pastis.models.lightning.pastis_utae_semantic.PastisUTAE
lr: 0.001
resume_from_checkpoint: null
lr_type: plateau

model:
  _target_: mmdc_downstream_pastis.models.torch.utae.UTAE
  input_dim: 22

metrics_list : ["cross_entropy"]

# To choose from ["RMSE", "MSE", "MAE"]
losses_list : ["cross_entropy"]
