
_target_: mmdc_downstream_pastis.models.lightning.pastis_utae_semantic.PastisUTAE
lr: 0.001
resume_from_checkpoint: ${oc.env:WORK}/results/MMDC/results/pastis/checkpoints/pastis_encoded_s1_asc_utae/2024-05-27_11-14-55/last.ckpt

model:
  _target_: mmdc_downstream_pastis.models.torch.utae.UTAE
#  in_channels: 10
#  num_classes: 20
  input_dim: 6

metrics_list : ["cross_entropy"]

# To choose from ["RMSE", "MSE", "MAE"]
losses_list : ["cross_entropy"]
