
_target_: mmdc_downstream_pastis.models.lightning.pastis_utae_semantic.PastisUTAE
lr: 0.001
resume_from_checkpoint: /work/scratch/data/kalinie/MMDC/results/pastis/checkpoints/pastis_encoded_concat_utae/2024-08-08_12-07-34/last.ckpt
lr_type: plateau

model:
  _target_: mmdc_downstream_pastis.models.torch.utae_fusion.UTAEFusion
  input_dim:
    S1: 6
    S2: 6
  fusion: concat

metrics_list : ["cross_entropy"]

# To choose from ["RMSE", "MSE", "MAE"]
losses_list : ["cross_entropy"]
