
_target_: mmdc_downstream_pastis.models.lightning.pastis_shallow_semantic.PastisShallow
lr: 0.001
resume_from_checkpoint: null #/work/scratch/data/kalinie/MMDC/results/pastis/checkpoints/pastis_encoded_alise_s1_asc/2024-12-10_16-49-17/last.ckpt
lr_type: plateau

model:
  _target_: mmdc_downstream_pastis.models.torch.shallow_big.ShallowBig
  input_dim: 640
  num_classes: 19

metrics_list : ["f1"]

# To choose from ["RMSE", "MSE", "MAE"]
losses_list : ["cross_entropy"]

margin: 5
