
_target_: mmdc_downstream_pastis.models.lightning.pastis_utae_semantic.PastisUTAE
lr: 0.001
resume_from_checkpoint: null #${oc.env:WORK}/results/MMDC/results/pastis/checkpoints/pastis_encoded_s1_utae/2024-07-15_10-35-49/last.ckpt
lr_type: plateau

model:
  _target_: mmdc_downstream_pastis.models.torch.utae.UTAE
  input_dim: 6

metrics_list : ["cross_entropy"]

# To choose from ["RMSE", "MSE", "MAE"]
losses_list : ["cross_entropy"]
