
_target_: mmdc_downstream_pastis.models.lightning.pastis_utae_semantic.PastisUTAE
lr: 0.001
resume_from_checkpoint: ${oc.env:WORK}/results/MMDC/results/pastis/checkpoints/pastis_encoded_s2_utae/2024-07-17_11-13-34/last.ckpt
lr_type: constant

model:
  _target_: mmdc_downstream_pastis.models.torch.utae.UTAE
  input_dim: 6

metrics_list : ["cross_entropy"]

# To choose from ["RMSE", "MSE", "MAE"]
losses_list : ["cross_entropy"]
