
_target_: mmdc_downstream_pastis.models.lightning.pastis_shallow_semantic.PastisShallow
lr: 0.0001
resume_from_checkpoint: null #/work/scratch/data/kalinie/MMDC/results/pastis/checkpoints/pastis_encoded_alise_s2/2024-10-29_06-47-24/last.ckpt
lr_type: plateau

model:
  _target_: mmdc_downstream_pastis.models.torch.shallow_big.ShallowBig
  input_dim: 320
  num_classes: 19

metrics_list : ["f1"]

# To choose from ["RMSE", "MSE", "MAE"]
losses_list : ["cross_entropy"]
