
_target_: mmdc_downstream_pastis.models.lightning.pastis_utae_semantic.PastisUTAE
lr: 0.001
resume_from_checkpoint: ${oc.env:WORK}/results/MMDC/results/pastis/checkpoints/pastis_oe_concat_utae_s1_asc_desc/2024-05-22_20-04-16/epoch_010.ckpt

model:
  _target_: mmdc_downstream_pastis.models.torch.utae_fusion.UTAEFusion
  input_dim:
    S1_ASC: 3
    S1_DESC: 3
  fusion: concat
  satellites: [ "S1_ASC", "S1_DESC" ]

metrics_list : ["cross_entropy"]

# To choose from ["RMSE", "MSE", "MAE"]
losses_list : ["cross_entropy"]
