
_target_: mmdc_downstream_pastis.models.lightning.pastis_utae_semantic.PastisUTAE
lr: 0.001
resume_from_checkpoint: ${oc.env:WORK}/results/MMDC/results/pastis/checkpoints/pastis_encoded_pvae_utae/2024-06-10_16-24-53/last.ckpt

model:
  _target_: mmdc_downstream_pastis.models.torch.utae.UTAE
  input_dim: 22

metrics_list : ["cross_entropy"]

# To choose from ["RMSE", "MSE", "MAE"]
losses_list : ["cross_entropy"]
