_target_: mmdc_downstream_lai.datamodules.datamodule_lai_flat.LAIDataModule

use_logvar: false
norm: false
selected_data: s2_lat # ["exp_lat", "s1_lat", "s2_lat", "s1_asc", "s1_desc", "s1_mask"]

#path_data:
#  _target_: mmdc_downstream_lai.datamodules.datamodule_lai_flat.DataPath
#  train : ${oc.env:WORK}/results/LAI/data_values_baseline_checkpoint_best_train.csv
#  val : ${oc.env:WORK}/results/LAI/data_values_baseline_checkpoint_best_val.csv
#  test : ${oc.env:WORK}/results/LAI/data_values_baseline_checkpoint_best_test.csv

#path_data:
#  _target_: mmdc_downstream_lai.datamodules.datamodule_lai_flat.DataPath
#  train : ${oc.env:WORK}/results/LAI/data_values_baseline_checkpoint_best_train.csv
#  val : ${oc.env:WORK}/results/LAI/data_values_baseline_checkpoint_best_val.csv
#  test : ${oc.env:WORK}/results/LAI/data_values_baseline_checkpoint_best_test.csv

path_data:
  _target_: mmdc_downstream_lai.datamodules.datamodule_lai_flat.DataPath
  train : ${oc.env:WORK}/results/MMDC/jobs/data_values_baseline_magical_checkpoint_train_s2.csv
  val : ${oc.env:WORK}/results/MMDC/jobs/data_values_baseline_magical_checkpoint_val_s2.csv
  test : ${oc.env:WORK}/results/MMDC/jobs/data_values_baseline_magical_checkpoint_test_s2.csv

batch_size:
  _target_: mmdc_downstream_lai.datamodules.datamodule_lai_flat.BatchSize
  train: 8192
  val: 409600
  test: 409600
