_target_: mmdc_downstream_pastis.datamodule.pastis_oe_only_satellite.PastisDataModule

data_folder: "/work/CESBIO/projects/MAESTRIA/PASTIS/PASTIS-R"
data_folder_oe: "/work/CESBIO/projects/DeepChange/Ekaterina/Pastis_OE"

task:
  _target_: mmdc_downstream_pastis.datamodule.pastis_oe_only_satellite.PASTISTask
#  target:
#    _target_: mtan_s1s2_classif.datamodules.pastis_dataset.PASTISTarget
#    name: SEMANTIC
  reference_date: "2018-10-01"
  class_mapping: null
  mono_date: null
  sats: [ "S2" ]

folds:
  _target_: mmdc_downstream_pastis.datamodule.datatypes.PastisFolds
  train: [1,2,3]
  val: [4]
  test: [5]

batch_size: 4
crop_size: 64
