_target_: mmdc_downstream_pastis.datamodule.pastis_encoded.PastisEncodedDataModule

dataset_path_oe: ${oc.env:WORK}/results/Pastis_encoded/2024-04-05_14-58-22
dataset_path_pastis: ${oc.env:SCRATCH}/scratch_data/Pastis

reference_date: "2018-10-01"
sats: [ "S1" ]
task: "semantic"

folds:
  _target_: mmdc_downstream_pastis.datamodule.datatypes.PastisFolds
  train: [1,2,3]
  val: [4]
  test: [5]

batch_size: 4
crop_size: 64
