_target_: mmdc_downstream_pastis.datamodule.pastis_encoded.PastisEncodedDataModule

dataset_path_oe: ${oc.env:WORK}/results/Pastis_encoded/pvae
dataset_path_pastis: ${oc.env:SCRATCH}/scratch_data/Pastis

reference_date: "2018-09-01"
sats: [ "S2" ]
task: "semantic"

folds:
  _target_: mmdc_downstream_pastis.datamodule.datatypes.PastisFolds
  train: [1,2,3]
  val: [4]
  test: [5]
#    fold_sequence = [
#        [[1, 2, 3], [4], [5]],
#        [[2, 3, 4], [5], [1]],
#        [[3, 4, 5], [1], [2]],
#        [[4, 5, 1], [2], [3]],
#        [[5, 1, 2], [3], [4]],
#    ]

batch_size: 5
crop_size: null
norm: true
use_logvar: true
