_target_: mmdc_downstream_pastis.datamodule.pastis_encoded.PastisEncodedDataModule

dataset_path_oe: ${oc.env:WORK}/results/Pastis_encoded/magical_checkpoint
dataset_path_pastis: ${oc.env:SCRATCH}/scratch_data/Pastis

reference_date: "2018-09-01"
sats: [ "S1_ASC" ]
task: "semantic"

folds:
  _target_: mmdc_downstream_pastis.datamodule.datatypes.PastisFolds
  train: [1,2,3]
  val: [4]
  test: [5]

batch_size: 4
crop_size: null
norm: false
use_logvar: false
